### PR TITLE
Add pr-feedback.yml

### PR DESCRIPTION
**Pull request by AndyScherzinger**

### CODE REVIEW

**Comment by provokateurin** [comment]
I didn't add it here intentionally because the template is for the community and there the feedback action is not needed or even confusing. IMO this should be reverted.

**Comment by AndyScherzinger** [comment]
If nobody outside the company ever opens a PR than it will also never trigger - so also no harm in having it in imho

**Comment by provokateurin** [comment]
No, I mean the template will be forked by community members. Then they also get this action but it is useless for them.
It's not about this specific repo but the repos that will be created from it.

**Comment by AndyScherzinger** [comment]
Ah, gotcha! Then let's remove it again 👍

**Comment by provokateurin** [comment]
Done, I reverted the commit.

**Pull request merged**
